manifest-version = 1

[project]
group = "dev.zonnedev.jman.example"
name = "library-grpc-api"
version = "1.0.0"
java-release = 25
packaging = "jar"
main-class = "dev.zonnedev.jman.example.grpc.GrpcApplication"

[path-dependencies]
"dev.zonnedev.jman.example:library-api-contracts" = "../api-contracts"
"dev.zonnedev.jman.example:library-application" = "../application"
"dev.zonnedev.jman.example:library-domain" = "../domain"

[dependencies.compile]
"com.google.protobuf:protobuf-java" = "4.36.1"
"io.grpc:grpc-api" = "1.83.0"
"io.grpc:grpc-netty-shaded" = "1.83.0"
"io.grpc:grpc-protobuf" = "1.83.0"
"io.grpc:grpc-stub" = "1.83.0"
"io.micronaut.grpc:micronaut-grpc-server-runtime" = "4.13.0"
"io.micronaut:micronaut-runtime" = "4.10.29"
"jakarta.inject:jakarta.inject-api" = "2.0.1"

[dependencies.runtime]
"org.yaml:snakeyaml" = "2.5"

[dependencies.test]
"org.junit.platform:junit-platform-console-standalone" = "1.12.2"

[annotation-processors]
"io.micronaut:micronaut-inject-java" = "4.10.29"
