manifest-version = 1

[project]
group = "dev.zonnedev.jman.example"
name = "library-client"
version = "1.0.0"
java-release = 25
packaging = "jar"

[path-dependencies]
"dev.zonnedev.jman.example:library-api-contracts" = "../api-contracts"

[dependencies.compile]
"com.fasterxml.jackson.core:jackson-databind" = "2.20.0"
"com.fasterxml.jackson.datatype:jackson-datatype-jdk8" = "2.20.0"
"com.google.protobuf:protobuf-java" = "4.36.1"
"io.grpc:grpc-api" = "1.83.0"
"io.grpc:grpc-netty-shaded" = "1.83.0"
"io.grpc:grpc-protobuf" = "1.83.0"
"io.grpc:grpc-stub" = "1.83.0"

[dependencies.test]
"org.junit.platform:junit-platform-console-standalone" = "1.12.2"
